//
//  Restaurant.swift
//  FoodieApp
//
//  Created by Quien on 2023-08-31.
//

import Foundation

struct Restaurant: Codable, Hashable, Comparable {
  static func < (lhs: Restaurant, rhs: Restaurant) -> Bool {
    lhs.id < rhs.id
  }
  
  let id: Int
  let name: String
  let cost: Int
  let timeCategories: [String]
  let foodCategories: [String]
  let imageURL: URL?
}

func sampleRestaurants() -> [Restaurant] {
  return [
    Restaurant(id: 1,
               name: "Kosoo Korean Chicken & BBQ Restaurant",
               cost: 2,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Korean", "Chicken"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/d5379d12-e2b8-4389-a26a-c8490f4fa1a6.jpeg")),
    Restaurant(id: 2,
               name: "SURA",
               cost: 3,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Korean", "Asian", "BBQ"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/c61a4fa6-8a24-4355-9c60-3e82884f4b69.jpeg")),
    Restaurant(id: 3,
               name: "Damso (Denman)",
               cost: 2,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Korean", "Asian", "BBQ"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/6b6f35dc-a73c-42a1-a0d7-056eaf7c0095.jpeg")),
    Restaurant(id: 4,
               name: "McDonald's (Robson)",
               cost: 1,
               timeCategories: ["Breakfast", "Brunch", "Lunch", "Dinner"],
               foodCategories: ["Burger", "Fast Food", "American"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/24550b09-09be-4ad4-afda-ccc7c666258b.jpeg")),
    Restaurant(id: 5,
               name: "Subway (Robson & Cambie)",
               cost: 1,
               timeCategories: ["Breakfast", "Brunch", "Lunch", "Dinner"],
               foodCategories: ["American", "Healthy", "Sandwich", "Salads", "Fast Food"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/eab773d2-eab2-4075-adb2-6bdd6fdbb6f9.jpeg")),
    Restaurant(id: 6,
               name: "A&W (Robson St)",
               cost: 1,
               timeCategories: ["Breakfast", "Brunch", "Lunch", "Dinner"],
               foodCategories: ["Burger", "American", "Fast Food"],
               imageURL: URL(string: "https://duyt4h9nfnj50.cloudfront.net/resized/bulk_actions_image_5f5f4bef-8ecd-4754-b5f7-5430eb47375f-w550-21.jpg")),
    Restaurant(id: 7,
               name: "7-Eleven",
               cost: 1,
               timeCategories: ["24/7"],
               foodCategories: ["Convenience", "Comfort Food", "Bakery", "Juice Bars", "Pizza", "Wings"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/8e8a1aa1-7cd1-49cc-9efc-689264f06504.jpeg")),
    Restaurant(id: 8,
               name: "Starbucks",
               cost: 2,
               timeCategories: ["Breakfast", "Brunch", "Lunch", "Dinner"],
               foodCategories: ["Bakery", "Cafe"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/0a2a4b68-b3f7-458a-98c8-bce6692fcb57.jpeg")),
    Restaurant(id: 9,
               name: "Tim Hortons",
               cost: 1,
               timeCategories: ["Breakfast", "Brunch", "Lunch", "Dinner"],
               foodCategories: ["Bakery", "Cafe", "Donuts"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/24ef7c52-1d50-4bdf-8793-0fef739b42f6.jpeg")),
    Restaurant(id: 10,
               name: "Gong Cha - Robson",
               cost: 1,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Bubble Tea", "Desserts"],
               imageURL: URL(string: "https://duyt4h9nfnj50.cloudfront.net/resized/1539810003470-w550-49.jpg")),
    Restaurant(id: 11,
               name: "Xing Fu Tang 幸福堂 (Cambie)",
               cost: 1,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Asian", "Desserts", "Juice and Smoothies", "Bubble Tea"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/6acbb538-6a33-457f-ba5e-da88ceb42c8b.jpeg")),
    Restaurant(id: 12,
               name: "ChongQing Restaurant (Robson)",
               cost: 2,
               timeCategories: ["Dinner"],
               foodCategories: ["Chinese", "Asian", "Asian Fusion"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/3d8eb288-d1cc-4c76-be38-2bcb9e140de0.jpeg")),
    Restaurant(id: 13,
               name: "KOKORO TOKYO MAZESOBA",
               cost: 2,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Japanese", "Asian"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/b70f2103-1186-405c-9252-2eae11188cde")),
    Restaurant(id: 14,
               name: "Miyako Sushi",
               cost: 2,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Japanese"],
               imageURL: URL(string: "https://duyt4h9nfnj50.cloudfront.net/resized/1536350917112-w550-dd.jpg")),
    Restaurant(id: 15,
               name: "Z&W Shanghai Kitchen",
               cost: 2,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Chinese", "Asian", "Asian Fusion"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/3337a3ff-457b-4d81-9b08-aaf6cfcc65d1.jpeg")),
    Restaurant(id: 16,
               name: "Banana Leaf (Davie Street)",
               cost: 2,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Malaysian", "Asian", "Asian Fusion"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/5e4667b3-8f0d-41af-9951-5f8dbf64c718.jpeg")),
    Restaurant(id: 17,
               name: "Adelitas",
               cost: 2,
               timeCategories: ["Breakfast", "Brunch", "Lunch", "Dinner"],
               foodCategories: ["Mexican", "Latin American", "New Mexican"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/af28b622-9432-4215-9f76-7700a99f417e.jpeg")),
    Restaurant(id: 18,
               name: "Rio Brazilian Steakhouse",
               cost: 2,
               timeCategories: ["Lunch", "Dinner"],
               foodCategories: ["Steak", "Brazilian", "BBQ"],
               imageURL: URL(string: "https://d1ralsognjng37.cloudfront.net/75bba1b2-1d4b-4bf8-9e2d-b25be4f0db44.jpeg")),
    Restaurant(id: 19,
               name: "3 Quarters Full Cafe",
               cost: 2,
               timeCategories: ["Brunch", "Lunch", "Dinner"],
               foodCategories: ["Taiwanese", "Asian", "Sandwich"],
               imageURL: URL(string: "https://duyt4h9nfnj50.cloudfront.net/resized/38dddf1c31155525f9391bc4d70b1d17-w550-0e.jpg")),
    Restaurant(id: 20,
               name: "Nammos Estiatorio",
               cost: 3,
               timeCategories: ["Dinner"],
               foodCategories: ["Mediterranean", "Greek"],
               imageURL: URL(string: "https://duyt4h9nfnj50.cloudfront.net/resized/1528724582320-w550-e5.jpg"))
  ]
}
